Import("env")
import os

# Load .env file
try:
    with open(".env", "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip()
                # Remove surrounding quotes if present
                if (value.startswith('"') and value.endswith('"')) or \
                   (value.startswith("'") and value.endswith("'")):
                    value = value[1:-1]
                os.environ[key] = value
                # Debug output for sensitive fields
                if key in ["NTFY_PASSWORD", "NTFY_USERNAME", "NTFY_TOKEN"]:
                    print(f"Loaded {key}: length={len(value)}")
except FileNotFoundError:
    print("Warning: .env file not found, using defaults from config.h")

# Inject environment variables as build flags
# Separate boolean flags from string values
bool_vars = {
    "LORA_ENABLED": os.environ.get("LORA_ENABLED", "true"),
    "DISCORD_ENABLED": os.environ.get("DISCORD_ENABLED", "false"),
    "NTFY_ENABLED": os.environ.get("NTFY_ENABLED", "true"),
    "EMAIL_ENABLED": os.environ.get("EMAIL_ENABLED", "false"),
    "WEBHOOK_ENABLED": os.environ.get("WEBHOOK_ENABLED", "false"),
    "NTFY_MESH_RELAY": os.environ.get("NTFY_MESH_RELAY", "true"),
    "DISCORD_MESH_RELAY": os.environ.get("DISCORD_MESH_RELAY", "true"),
    "WEBHOOK_MESH_RELAY": os.environ.get("WEBHOOK_MESH_RELAY", "false"),
    "EMAIL_MESH_RELAY": os.environ.get("EMAIL_MESH_RELAY", "false"),
}

string_vars = {
    # WiFi Configuration
    "WIFI_SSID": os.environ.get("WIFI_SSID", "your_wifi_ssid"),
    "WIFI_PASSWORD": os.environ.get("WIFI_PASSWORD", "your_wifi_password"),

    # Admin Authentication
    "ADMIN_USERNAME": os.environ.get("ADMIN_USERNAME", "admin"),
    "ADMIN_PASSWORD": os.environ.get("ADMIN_PASSWORD", "admin"),

    # LoRa/MeshCore Channel Configuration
    "CHANNEL_NAME": os.environ.get("CHANNEL_NAME", "BCAlerts"),
    "CHANNEL_SECRET": os.environ.get("CHANNEL_SECRET", ""),
    
    # Discord Configuration
    "DISCORD_WEBHOOK_URL": os.environ.get("DISCORD_WEBHOOK_URL", ""),
    
    # Ntfy Configuration
    "NTFY_SERVER": os.environ.get("NTFY_SERVER", "https://ntfy.sh"),
    "NTFY_TOPIC": os.environ.get("NTFY_TOPIC", "esp32_uptime"),
    "NTFY_USERNAME": os.environ.get("NTFY_USERNAME", ""),
    "NTFY_PASSWORD": os.environ.get("NTFY_PASSWORD", ""),
    "NTFY_TOKEN": os.environ.get("NTFY_TOKEN", ""),
    
    # Email/SMTP Configuration
    "SMTP_HOST": os.environ.get("SMTP_HOST", "smtp.gmail.com"),
    "SMTP_PORT": os.environ.get("SMTP_PORT", "587"),
    "EMAIL_RECIPIENT": os.environ.get("EMAIL_RECIPIENT", ""),
    "EMAIL_SENDER": os.environ.get("EMAIL_SENDER", ""),
    "SMTP_USER": os.environ.get("SMTP_USER", ""),
    "SMTP_PASSWORD": os.environ.get("SMTP_PASSWORD", ""),
    
    # Generic Webhook Configuration
    "WEBHOOK_URL": os.environ.get("WEBHOOK_URL", ""),
    "WEBHOOK_METHOD": os.environ.get("WEBHOOK_METHOD", "POST"),
}

# Numeric vars (no quotes)
int_vars = {
    "LED_PIN": os.environ.get("LED_PIN", "35"),
    "LORA_SPREADING_FACTOR": os.environ.get("LORA_SPREADING_FACTOR", "7"),
    "LORA_CODING_RATE": os.environ.get("LORA_CODING_RATE", "5"),
}

# Float vars (no quotes)
float_vars = {
    "LORA_FREQ": os.environ.get("LORA_FREQ", "915.0"),
    "LORA_BANDWIDTH": os.environ.get("LORA_BANDWIDTH", "125.0"),
}

# Handle boolean values (no quotes needed for preprocessor)
bool_defines = {}
for key, value in bool_vars.items():
    bool_value = value.lower() in ['true', '1', 'yes', 'on']
    bool_defines[key] = '1' if bool_value else '0'
    env.Append(CPPDEFINES=[(key, bool_defines[key])])

# Generate a header for string values to avoid shell/SCons mangling of characters like '$'
header_lines = [
    "// Auto-generated by load_env.py. Do not edit manually.",
    "#pragma once",
    ""
]

def c_escape(val: str) -> str:
    return val.replace('\\', '\\\\').replace('"', '\\"')

for key, value in string_vars.items():
    if key in ["NTFY_PASSWORD", "NTFY_USERNAME", "NTFY_TOKEN"]:
        print(f"Injecting {key}: original_len={len(os.environ.get(key, ''))}, escaped_len={len(value)}")
    escaped = c_escape(value)
    header_lines.append(f'#define {key} "{escaped}"')

for key, value in int_vars.items():
    header_lines.append(f'#define {key} {value}')

for key, value in float_vars.items():
    header_lines.append(f'#define {key} {value}')

for key, value in bool_defines.items():
    header_lines.append(f'#define {key} {value}')

os.makedirs("include", exist_ok=True)
header_path = os.path.join("include", "generated_env.h")
with open(header_path, "w", encoding="ascii") as header_file:
    header_file.write("\n".join(header_lines))
print(f"Wrote {header_path}")
