// Auto-generated by load_env.py. Do not edit manually.
#pragma once

#define WIFI_SSID "Nacho Wi-Fi"
#define WIFI_PASSWORD "brownCow36"
#define ADMIN_USERNAME "admin"
#define ADMIN_PASSWORD "admin"
#define CHANNEL_NAME "BCAlerts"
#define CHANNEL_SECRET "f7d32d9d09982b83c2c1086a5ea2239a"
#define DISCORD_WEBHOOK_URL "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN"
#define NTFY_SERVER "https://ntfy.hawkinsit.au"
#define NTFY_TOPIC "esp32-uptime"
#define NTFY_USERNAME "brad"
#define NTFY_PASSWORD "*E6k@IUw$NwNr9^1WtbanWIhhE8Ic^lZ"
#define NTFY_TOKEN ""
#define SMTP_HOST "smtp.gmail.com"
#define SMTP_PORT "587"
#define EMAIL_RECIPIENT "recipient@example.com"
#define EMAIL_SENDER "esp32@example.com"
#define SMTP_USER "your_email@gmail.com"
#define SMTP_PASSWORD "your_app_specific_password"
#define WEBHOOK_URL "https://example.com/webhook"
#define WEBHOOK_METHOD "POST"
#define LORA_ENABLED 0
#define DISCORD_ENABLED 0
#define NTFY_ENABLED 1
#define EMAIL_ENABLED 0
#define WEBHOOK_ENABLED 0
#define NTFY_MESH_RELAY 1
#define DISCORD_MESH_RELAY 0
#define WEBHOOK_MESH_RELAY 0
#define EMAIL_MESH_RELAY 0